services:
  - type: web
    name: snapsheets
    env: python
    rootDir: backend
    buildCommand: bash build.sh
    startCommand: gunicorn -w 2 -k uvicorn.workers.UvicornWorker app.main:app
    healthCheckPath: /health
    autoDeploy: true
